# Generated by Django 2.0.3 on 2018-04-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionKey', models.CharField(max_length=40)),
                ('Question1', models.CharField(max_length=40)),
                ('Question2', models.CharField(max_length=40)),
                ('Question3', models.CharField(max_length=40)),
                ('Question4', models.CharField(max_length=40)),
                ('Question5', models.CharField(max_length=40)),
                ('Question6', models.CharField(max_length=40)),
                ('Question7', models.TextField(max_length=40)),
                ('Question8', models.TextField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Questionnaire Results',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionKey', models.CharField(max_length=40)),
                ('StatementPath', models.TextField()),
                ('TemplatesUsed', models.BooleanField(default=False)),
                ('ReasonGiven', models.BooleanField(default=False)),
                ('TopicComplete', models.BooleanField(default=False)),
                ('CurrentStatement', models.CharField(default='', max_length=100)),
                ('CurrentTopic', models.CharField(default='', max_length=100)),
                ('Topics', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('topic', models.CharField(max_length=40)),
                ('sentiment', models.CharField(max_length=40)),
                ('counters', models.CharField(max_length=200)),
                ('response', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Statements',
            },
        ),
    ]
